
# Exo1
FROM alpine:3.7

# Créer une image docker avec Git et Curl installés
RUN apk update 
RUN apk add git 
RUN apk add curl

# Tager l'image exo1:1.0
# Exécuter une instance à partir de l'image

# Vérifier l'exécution de Git et de Curl
CMD ["/bin/sh git --version"]

# Note: vous pouvez me fournir le Dockerfile par le moyen de votre choix